### ISSUE TITLE
Print out failed repositories at the end

### ISSUE THREAD

**Issue by jodator** [cksource/mgit2#104]
Right now if a `mgit` command fails in some repository you have to scroll the cosnole to find out in which:

```
43 packages have been processed.
Execution time: 47s216ms.

❗❗❗ The command failed to execute in 1 repository.
```

It would be nice if the failed repositories would be listed below the error:

```
43 packages have been processed.
Execution time: 47s216ms.

❗❗❗ The command failed to execute in 1 repository:
    - @ckeditor/ckeditor5-mention
```

At the moment we have **43** repositories and the number will grow. It would be nice to have quick overview in which repositories a command have failed so you can for instance copy the list to process each repo.

**Comment by Reinmar** [comment]
BIg 👍 for this. Should be easy to add and would save me a lot of time.

**Comment by Reinmar** [comment]
I miss this every day, so I raised the priority.
