### ISSUE TITLE
bootstrap + update -> pull

### ISSUE THREAD

**Issue by Reinmar** [cksource/mgit2#11]
I can see that the bootstrap and update commands are very similar. I wanted to have `mgit bootstrap` to follow Lerna's naming, but it doesn't make sense in case of mgit. Mgit clones repos and pulls changes, which is a bit different job. Let's have a single `mgit pull` command for that. It will be used to init the repositories and later to pull changes to them.

WDYT?

**Comment by pjasiun** [comment]
:+1: I like it, but since it do more than just `pull` on multiple repos the command `mgit pull` would be confusing. I prefer `mgit update`.

**Comment by Reinmar** [comment]
`mgit update` makes sense. Neither connected to any git command nor to Lerna, which is fine, because it's unique.

**Comment by Reinmar** [comment]
Let's discuss this further in https://github.com/cksource/mgit2/issues/73.
