### ISSUE TITLE
Header styling is invisible on Travis

### ISSUE THREAD

**Issue by Reinmar** [cksource/mgit2#19]
![image](https://cloud.githubusercontent.com/assets/156149/22060548/84486b36-dd71-11e6-8b7e-abe4908f4f6e.png)

We can either use ASCII (e.g. precede the name with `# <name>`) or use different colors. Apparently, Travis ignores inverse().

**Comment by pomek** [comment]
`git clone` logs should also be gray. 

I'm for the `# <name>` and leave current colors as it is now.

**Comment by Reinmar** [comment]
That's how it looks in my console now:

![image](https://cloud.githubusercontent.com/assets/156149/22111504/d36133f8-de5f-11e6-9126-c68bdc022eb0.png)

Should be fine in Travis as well now.

**Comment by Reinmar** [comment]
![image](https://cloud.githubusercontent.com/assets/156149/22113306/19a365ce-de66-11e6-9610-4e76a14966fd.png)
