### ISSUE TITLE
Repository-resolver could return directory name

### ISSUE THREAD

**Issue by pomek** [cksource/mgit2#20]
At this moment, repository resolver returns two things:

1. repository URL,
2. branch to clone (most common it is `master`).

It is enough for case - mgit reads the `mgit.json` file.

But, if `bootstrap` command is called with option `--recursive`, the `package.json` file of cloned package is also read. Mgit will install all required dependencies by cloned package.

Resolver does not allow to change a directory for an installed package. Mgit will always install in the directory: `packages/{ packageName }`. Would be nice to have configurable the directory for packages required by other packages.

Repository resolver could return three things:

1. repository URL,
2. branch to clone,
3. the directory name.

It allows removing the [npm scope](https://docs.npmjs.com/misc/scope) from package name. It means, a package `@organization/some-package` would be installed under `packages/some-package` instead of `packages/@organization/some-package` as it is now.

**Comment by Reinmar** [comment]
👍
