### ISSUE TITLE
Should bootstrap add recursively cloned packages to mgit.json?

### ISSUE THREAD

**Issue by Reinmar** [cksource/mgit2#21]
Right now if you clone repos recursively and try to do `mgit exec` only the packages listed in `mgit.json` will be included.

So either they should be added there automatically (makes some sense) or exec and update tasks should read packages by scanning the `packages/` directory rather than based on `mgit.json`.

**Comment by pomek** [comment]
Both options make sense for me.

I'm for the first option - update the `mgit.json` file. We can use the `afterExecute` hook for `bootstrap command for it. 

I have a question - do we need a validator which checks whether the package name can be used as a repository URL? For example - `gulp` as a dependency cannot be installed from `gulp`. It must be `gulpjs/gulp`. How to we want to resolve it?

**Comment by Reinmar** [comment]
> How to we want to resolve it?

Your resolver should not try to install gulp from git. Our resolver returns null for anything which is not CKEditor 5 package.

**Comment by Reinmar** [comment]
OK, I can see now that `mgit exec` must work differently anyway. It doesn't work now at all in the `ckeditor5` repository because it uses package names to look for directories (and as we now thanks to https://github.com/cksource/mgit2/issues/23 that's wrong).
