### ISSUE TITLE
The execute command does not work if package names don't match directory names

### ISSUE THREAD

**Issue by Reinmar** [cksource/mgit2#25]
Happens in `ckeditor5` now due to https://github.com/cksource/mgit2/issues/23. Related to https://github.com/cksource/mgit2/issues/21.

First I thought that we have two options:

* use the resolver to find directory name (like the other commands do, so part of that logic could be extracted to a util),
* run the command on directories found in `packages/`, not on dependencies found in `mgit.json`.

The latter sounds simpler, but it'd be incorrect. Since a resolver can return any `a/b/c` directory name (e.g. a scoped dir like `@org/repo`), then a command would fail in such a case.

BTW, the next step would be to add `--recursive` option to the exec command too. It should have the same behaviour as in other commands. We start with what is defined in `mgit.json` and if `--recursive` is defined we go deeper.

**Comment by Reinmar** [comment]
Ofc, support for `--recursive` is a separate ticket.

**Comment by pomek** [comment]
Update command also does not work:

![image](https://cloud.githubusercontent.com/assets/2270764/22139557/0b64df48-dee7-11e6-959e-dcb363ff3f26.png)
