### ISSUE TITLE
Introduce `mgit save-hashes` command

### ISSUE THREAD

**Issue by pjasiun** [cksource/mgit2#27]
`mgit update` set versions in `packages` folder to the versions defined in `mgit.json` file. But the opposite command would be also needed, to set versions in `mgit.json` to hashes in the `packages`.

I propose the `mgit save-hashes` command which goes into each repository check the current hash and add `#hash` to each entry in `mgit.json`. It's very useful if the project uses fixed versions of dependencies and update them manually.

**Comment by pomek** [comment]
It can be also helpful for the tool for saving revisions in CKE5.

At this moment, we have to do it manually - https://github.com/ckeditor/ckeditor5-dev/blob/t/ckeditor5-revisions/1/packages/ckeditor5-dev-env/bin/save-revision.js.

**Comment by pomek** [comment]
Looks like work as I expected: https://github.com/ckeditor/ckeditor5/commit/b55508d70128537e5af15c81b62ff8a329963abd

**Comment by pomek** [comment]
I would call this command `dump` because this reminds me with the database dump.

**Comment by Reinmar** [comment]
Turns out I wanted to name it exactly like PJ proposed: https://github.com/cksource/mgit2/pull/38#discussion_r98629166 ;) So better to stick to that.

**Comment by pomek** [comment]
Ok…

![image](https://cloud.githubusercontent.com/assets/2270764/22460276/5dfda896-e7a4-11e6-83b7-a0578289e5ef.png)
