### ISSUE TITLE
Are scopes ignored?

### ISSUE THREAD

**Issue by pjasiun** [cksource/mgit2#28]
In the readme I see:

> Package will be installed in packages/@scope/package-name and checked out to branch develop. It will be cloned from git@github.com:organization/repository.git:
> 
>```
>{
>    "@scope/package-name": "organization/repository#develop"
>}
>```

At the save time when I added:

```json
{
  "packages": "packages/",
  "dependencies": {
    "@ckeditor/ckeditor5-engine": "ckeditor/ckeditor5-engine"
  }
}
```

and run `mgit bootstrap` I found the project in the `packages/ckeditor5-engine/` folder.

Is it a bug, mistake in readme or I don't understand something?

**Comment by pjasiun** [comment]
This difference between dependency name and the folder name makes using external tools and scripts working with the structure created by `mgit` much harder.

For instance, I can not simply tell Webpack where it should resolve dependencies. Or, if I want to create a script which goes through subprojects and do something with them it hard to find where these projects are.

**Comment by Reinmar** [comment]
The readme is outdated. See https://github.com/cksource/mgit2/issues/23.
