### ISSUE TITLE
Update packages to specify commit does not work

### ISSUE THREAD

**Issue by pomek** [cksource/mgit2#34]
Mgit allows installing packages based on specify branch, tag or even commit id.

Unfortunately, mgit cannot update the package by checking out to specify commit id.

#### Steps to reproduce:

1. Check out a package to `master`
2. Add some commit id to `mgit.json` as a branch
3. Execute `mgit update`.

#### Expected behavior:

Modified package will be checked out to a specify commit.

#### Actual behavior:

Console logs:

```bash
(node:61534) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: msg.trim is not a function
```

**Comment by Reinmar** [comment]
That was working after https://github.com/cksource/mgit2/issues/24. Are you sure that you checked this with the latest version?

**Comment by Reinmar** [comment]
Ok, I see that #24 was about the bootstrap command.
