### ISSUE TITLE
Too many files are installed

### ISSUE THREAD

**Issue by Comandeer** [cksource/mgit2#37]
After installing mgit via npm (`npm install mgit2`), I've checked out of curiosity the contents of its directory and I saw `tests` dir, `.travis.yml`, `gulpfile.js` etc. These files are needed only for developing mgit, not for using it.

Maybe it could be fine to just whitelist needed file (`index.js` and `lib/` dir) using `files` field in `package.json` (npm always include `package.json`, readme, changelog and license anyway)? Or just blacklist all the files using `.npmignore`?

**Comment by pomek** [comment]
Changes introduced in 71d2840 does not work…

Npm does not install the `lib` directory. 

![image](https://cloud.githubusercontent.com/assets/2270764/22504575/52c7f980-e877-11e6-8911-c2e628962fd0.png)

![image](https://cloud.githubusercontent.com/assets/2270764/22504581/59d7a34c-e877-11e6-919f-6432a2f476cf.png)

**Comment by pomek** [comment]
Now it should work. I followed [package.json in Gulp](https://github.com/gulpjs/gulp/blob/master/package.json#L17-L22). 

Sorry for the mistake :(

In package.json should be names, not paths.

**Comment by pomek** [comment]
It works as I expected in the latest (0.5.1) version.
