### ISSUE TITLE
Error message from git update is not helpful.

### ISSUE THREAD

**Issue by ma2ciek** [cksource/mgit2#41]
I've got following error after `git update`: 

``` 
(node:11920) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: msg.trim is not a function
```

I checked packages and one of them was on the other branch that needs to merge after `git pull`
```
 #  @ckeditor/ckeditor5-utils                                            16/18 (89%) 
Your configuration specifies to merge with the ref 'refs/heads/t/116'
from the remote, but no such ref was fetched.
```

So the error from `git update` could be similar to provide a useful insight into the problem.

**Comment by pomek** [comment]
Would be nice to have some steps to reproduce. It speeds up the fix.

**Comment by ma2ciek** [comment]
Aw, I read the message once again and it was particularly my fault to pull already not-existing branch.

mgit.json:
