### ISSUE TITLE
Known errors should not be logged as crashes

### ISSUE THREAD

**Issue by Reinmar** [cksource/mgit2#45]
![image](https://cloud.githubusercontent.com/assets/156149/22894079/04782f84-f218-11e6-8d12-4b966dce043a.png)

I may be the author of this, but I was confused whether the tool failed gracefully or heavily. If we catch an issue, it shouldn't be that verbose. We just need the message to be logged.

**Comment by pomek** [comment]
After merging #44 we have 100% CC for commands, so we can improve it now. I will correct it.
