### ISSUE TITLE
mgit update pulls changes when it should abort

### ISSUE THREAD

**Issue by Reinmar** [cksource/mgit2#5]
Changes are pulled regardless of the fact that there are uncommitted changes in a certain repo.

Do e.g. this:

```
cd packages/ckeditor5-typing
git reset --hard HEAD~
touch x

cd ../..
mgit update
```

Output: 

```
 ckeditor5-typing
Package "ckeditor5-typing" has uncommitted changes. Aborted.
```

But the changes were pulled anyway.

**Comment by pomek** [comment]
The promises should not be split :/

![image](https://cloud.githubusercontent.com/assets/2270764/21900484/43cf26a2-d8f4-11e6-871d-8fb4fc2513bf.png)

We need to find other solution for this code.
