### ISSUE TITLE
Mgit status should highlight all non-master rows

### ISSUE THREAD

**Issue by oleq** [cksource/mgit2#55]
ATM mgit highlights only the branches which:
* are different than the entry in the `mgit.json`, 
* have unstaged files.

My point is that this pink color should help developers to focus on what belongs to the branch constellation and what does not. The most common case is that `mgit.json` is already configured.

![image](https://user-images.githubusercontent.com/1099479/29356032-387cbdc2-8273-11e7-915f-856664720036.png)

**Comment by pomek** [comment]
Let me clarified – mgit highlights branch **only** if the current branch is other than an entry in `mgit.json`.

But I agree – the row should be highlighted when current branch is other than master (instead of competition with `mgit.json`).

**Comment by Reinmar** [comment]
Actually, both information would be useful. One, that the branch is different than in `mgit.json` and two, that the branch is different than master. The first information is less important so we could find a less visible way to mark it – maybe with some `!` character next to the branch name?
