### ISSUE TITLE
Option for saving branches

### ISSUE THREAD

**Issue by oskarwrobel** [cksource/mgit2#66]
There is a `save-hashes` option what is really nice but It would be useful to have `save-branches` option. Hashes are nice if you want to bump packages at the end of your work, but when you are in the middle of something you may want to push set of branches.

WDYT?

**Comment by pomek** [comment]
May the `save-hashes` command could accept an option `--branch` which would do things as you described above.

**Comment by Reinmar** [comment]
Ekhm... `save-hashes --no-hashes-but-branches`? ;)

Doesn't `mgit save-branches` sound like it?

**Comment by pomek** [comment]
I don't see any reason for creating another command which does the same things with other data.

`save-hashes` => `save (hash|branch)` (additional argument for save command) or `save --branch`. If the `--branch` is missing, hashes will be saved by default.

**Comment by Reinmar** [comment]
Let's discuss this further in https://github.com/cksource/mgit2/issues/73.
