### ISSUE TITLE
mgit st does not include deleted (unstaged) files

### ISSUE THREAD

**Issue by oleq** [cksource/mgit2#67]
It gives a false feeling of having the repos clean, while in fact, they have unstaged changes that need committing. They should be displayed as modified (to KISS).

cc @pomek

```
(t/119 33c7e0d M5) oleq@MBP ~/...ckeditor5/packages/ckeditor5-theme-lark> git st
On branch t/119
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    theme/ckeditor5-basic-styles/code.css
	deleted:    theme/ckeditor5-block-quote/blockquote.css
	deleted:    theme/ckeditor5-image/image.css
	deleted:    theme/ckeditor5-image/imagecaption.css
	deleted:    theme/ckeditor5-image/imagestyle.css
```

```
oleq@MBP ~/CK/5/ckeditor5> mgit st
Collecting statuses...
┌──────────────────┬─────────┬─────────┬────────┐
│ Package          │ Branch  │ Commit  │ Status │
├──────────────────┼─────────┼─────────┼────────┤
...
│ theme-lark       │ ! t/119 │ 33c7e0d │        │
...
└──────────────────┴─────────┴─────────┴────────┘
```

**Comment by pomek** [comment]
![image](https://user-images.githubusercontent.com/2270764/35860509-8f98b688-0b44-11e8-9c78-ae0b164412de.png)

![image](https://user-images.githubusercontent.com/2270764/35860512-94da7dd4-0b44-11e8-8605-5174ea9f70a1.png)

Did you update mgit to the latest version?

```bash
mgit -v
0.7.2
```

**Comment by oleq** [comment]
Yes
```
mgit -v
0.7.2
```

**Comment by pomek** [comment]
This ticket is a dup of #58. We recently fixed it but the mgit haven't been released yet.

@Reinmar, could you handle it?

**Comment by Reinmar** [comment]
Yep. Sorry!

**Comment by oleq** [comment]
That explains why I couldn't find the DUP. It's been already closed 😜
