### ISSUE TITLE
mgit exec doesn't log headers

### ISSUE THREAD

**Issue by Reinmar** [cksource/mgit2#7]
```
(t/389 57e3859 ?1) p@m /www/ckeditor5/ckeditor5> mgit exec "node /www/ckeditor5/ckeditor5/scripts/switch-to-scoped-imports.js"
Execution time: 2s 27678ms.
```

I'd like to have repo headers (these white bars) in this case too, because I didn't even know whether it executed correctly.

**Comment by pomek** [comment]
Fixed. Now it looks:

*Command does not print anything on the output*
![image](https://cloud.githubusercontent.com/assets/2270764/21926380/c9f08d6a-d981-11e6-8796-c9a133b70c93.png)

*Command prints on stdout*
![image](https://cloud.githubusercontent.com/assets/2270764/21926445/fc73574a-d981-11e6-971b-41c67a299fa7.png)

*Command prints on stderr*
![image](https://cloud.githubusercontent.com/assets/2270764/21926425/ee9e5412-d981-11e6-93aa-5e450a570d78.png)
