### ISSUE TITLE
Be able to execute mgit command from nested directories

### ISSUE THREAD

**Issue by adelura** [cksource/mgit2#71]
Currently, it's possible to execute the _mgit_ command  **only** from a root directory. How about if it will be possible to execute from a nested directory like _packages/package-one_? Then _mgit_ will resolve root directory and change cwd to root one.

**Comment by Reinmar** [comment]
Hi @adelura! :D

This ticket DUPs https://github.com/cksource/mgit2/issues/1.

**Comment by adelura** [comment]
Oh sorry, I saw that #1 but didn't realise that it's the same.
