### ISSUE TITLE
Allow overriding package names in packages/*

### ISSUE THREAD

**Issue by Reinmar** [cksource/mgit2#72]
I wanted to add the `@ckeditor/ckeditor-cloud-services-core` package to the ckeditor5 repository, but since it starts with `ckeditor-` instead of `ckeditor5-` there are a lot of problems with all the tools which expect the `packages/ckeditor5-*/...` directory structure.

So, I create such an `mgit.json`:

```json
{
  "packages": "packages/",
  "packagesPrefix": "@ckeditor/ckeditor5-",
  "dependencies": {
    ...
    "@ckeditor/ckeditor5-clipboard": "ckeditor/ckeditor5-clipboard",
    "@ckeditor/ckeditor5-cloud-services": "ckeditor/ckeditor5-cloud-services",
    "@ckeditor/ckeditor5-cloud-services-core": "ckeditor/ckeditor-cloud-services-core",
    "@ckeditor/ckeditor5-core": "ckeditor/ckeditor5-core",
    "@ckeditor/ckeditor5-easy-image": "ckeditor/ckeditor5-easy-image",
    "@ckeditor/ckeditor5-editor-balloon": "ckeditor/ckeditor5-editor-balloon",
    ...
  }
}
```

And it kinda works. But not really. `mgit st`, `mgit exec`, `mgit update`, all except that this package is in `packages/ckeditor-cloud-services-core` while I want it to be in `packages/ckeditor5-cloud-services-core`.

Unfortunately, in general, `mgit.json` stores `pkg name => repo URL` pairs so, what I tried to do was wrong.

We need to find a different way. And perhaps this is a good moment to ensure that the whole `packages/` structure is simpler. 

E.g. such a config might be supported:

```json
{
  "packages": "packages/",
  "packagesPrefix": "@ckeditor/ckeditor5-",
  "dependencies": {
    ...
    "@ckeditor/ckeditor5-clipboard": "ckeditor/ckeditor5-clipboard",
    "@ckeditor/ckeditor5-cloud-services": "ckeditor/ckeditor5-cloud-services",
    "@ckeditor/ckeditor5-cloud-services-core": "ckeditor/ckeditor-cloud-services-core",
    "@ckeditor/ckeditor5-core": "ckeditor/ckeditor5-core",
    "@ckeditor/ckeditor5-easy-image": "ckeditor/ckeditor5-easy-image",
    "@ckeditor/ckeditor5-editor-balloon": "ckeditor/ckeditor5-editor-balloon",
    ...
  },
  "overrideDirectoryNames": {
      "@ckeditor/ckeditor5-cloud-services-core": "cloud-services-core"
  }
}
```

Which would result in cloning all this into:

```
packages/
    clipboard/
    cloud-services/
    cloud-services-core/
    core/
    easy-image/
    editor-balloon/
```

As you can see, I also removed the `ckeditor5-` prefix from directory names. This could be based on the `packagesPrefix` property which shouldn't also be applied to the `mgit st` command, but to the directory names.

**Comment by Reinmar** [comment]
BTW, to make it easier for you – we already strip the `@ckeditor/` part from package name when creating directory name. So, it would change to:

```
const directoryName = packageName.replace( config.packagesPrefix, '' );
```

Plus, the additional rules defined in `config.overrideDirectoryNames`.

PS. `mgit st` would print out directory names, `mgit exec --scope` should accept directory names (it's inconvenient today that it requires full pkg names), etc. But, then... what should `mgit update` print? It prints pkg names today. Should it print the shortened names?

**Comment by pomek** [comment]
> mgit exec --scope should accept directory names (it's inconvenient today that it requires full pkg names)

It works the same way as Lerna which was our pattern.

**Comment by Reinmar** [comment]
> It works the same way as Lerna which was our pattern.

Hmm... I forgot about Lerna. Perhaps these two methods could work - short or full names.

**Comment by oleq** [comment]
IIRC removing this prefix could [break the binding between styles and their counterparts](https://github.com/ckeditor/ckeditor5-build-classic/issues/41#issuecomment-374555661) in themes (e.g. ckeditor5-theme-lark).

**Comment by Reinmar** [comment]
Does it base on directory names or import names?

**Comment by oleq** [comment]
It uses paths https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/ckeditor5-dev-utils/lib/styles/utils/getpackagename.js#L37

**Comment by Reinmar** [comment]
I think that @pomek had the idea to use `package.json` to get the pkg name? Any chance that it'd work?

**Comment by ma2ciek** [comment]
Can't we use the full name here? We'd avoid the whole magic thing here. And we could just use `yarn test --files ckeditor5-cloud-services-core`, `yarn test --files ckeditor5-utils` to run tests. Or, as the second option, we could try to match directories starting with the `ckeditor` prefix.

**Comment by pomek** [comment]
I am strongly against modifying packages structure to this:

```
packages/
    clipboard/
    cloud-services/
```

Because it will break everything that we assumed in the past (it will break more than our dev env).

Because the main goal of the topic is about changing a package directory, I would like to do using the simplest solution that came to my head:

```json
{
  "packages": {
    "@foo/bar": "foo/bar"
  },
  "overrideDirectoryNames": {
    "@foo/bar": "custom-directory"
  }
}
```

Where: `packages` keeps `pkg name => repository` and `overrideDirectoryNames` keeps `pkg name => directory`. Mgit is able to resolve directory based on values in packages so if overrideDirectoryNames is not specified, nothing will happen.

Then `packagesPrefix` could be an array because if we need to use the `overrideDirectoryNames`, most probably the package does not patch to the prefix.

**Comment by Reinmar** [comment]
I might've known that you don't plan to change the directory names, but I forgot about that. And in https://github.com/ckeditor/ckeditor5/pull/1467#pullrequestreview-261917383 I R-ed your PR because of that.

To make a decision, we should understand more clearly why we have to keep the current directory names and why we can't rename them. Because the alternative (what you proposed in your PR) creates a strange situation where the pkg directory name is a bit different from its npm pkg name. This can be confusing.

**Comment by Reinmar** [comment]
In other words – I'd like to see the exact problems that we'd have in removing `ckeditor5-` prefixes so we can assess how much work would they require.

**Comment by pomek** [comment]
Everything is about our test environment. We couldn't remove `ckeditor5-` prefix because of PostCSS implementation. AFAIR it depends somehow on the prefix. I won't be too precise because I don't have any knowledge about it. @oleq, do you remember anything?

**Comment by Reinmar** [comment]
You mean https://github.com/cksource/mgit2/issues/72#issuecomment-376171710, I guess.
