### ISSUE TITLE
npm run reinstall without changing branches

### ISSUE THREAD

**Issue by scofalik** [cksource/mgit2#83]
I constantly get to this during my workflow that I want to do everything that `npm run reinstall` does but without changing branches I am on. And it is frustrating that I can't. So I propose renaming `npm run reinstall` to `npm run reset` (or `init` or `reinit`) and keep `reinstall` as a command that would just, well, reinstall stuff.

**Comment by Reinmar** [comment]
Yyy... -> ckeditor/ckeditor5?
