### ISSUE TITLE
Rethink name of this package

### ISSUE THREAD

**Issue by jodator** [cksource/mgit2#85]
We're using `mgit2` as a name of a package as we forked the `mgit` tool. The name of this tool is a bit unfortunate so we might think how to name it (besides `mgit3`).

My propositions:
- `ogit` as owesome (dead joke) git
- `pgit` as pararel git
- `mrgit` as multi-repo git
- `tigm` (as `tig` is already reserved)
- `kgit` similiary typed as `mgit`

**Comment by oleq** [comment]
To me, it does not matter as long as it is fast to type because this is something I'll type many times each day. `ogit` and `pgit`feel like the most convenient to type for me e.g. unlike `tigm`.

**Comment by jodator** [comment]
@oleq That's why I've researched free npm terms and those are free & fast to write (first letter on the right side of keyboard): `ogit`, `pgit`, `kgit`. With `kgit` being the most "ergonomic" to type...

**Comment by neumann-d** [comment]
I would suggest a more fancy name like `repomonkey` (just a stupid example), which is longer, but maybe more catchy for the users.

**Comment by Reinmar** [comment]
Just a reminder that we need to change this name finally :D https://github.com/ckeditor/ckeditor5/issues/330#issuecomment-493792558

**Comment by Reinmar** [comment]
The problem with a longer name is that we'd need to type it all the time. Unless there's some shorthand for that. So, e.g. for repomonkey it could be rpm, but rpm is unfortunately already taken (and the package name should be the same as the command name, as we've just learned). BTW, rpm is funny because running it will increase your CPU's rpm 🤪

From the proposals that I liked (let's hope no one will troll us and reserve those names):

* mrgit (reads as "mr. git")
* mugit (from multi-git – extensions of today's mgit)

I think both are easy to type (although, mugit better than mrgit for me) and sound well too. WDYT?

**Comment by pomek** [comment]
TBH, I don't see any problem with `mgit` name.

**Comment by Reinmar** [comment]
> TBH, I don't see any problem with `mgit` name.

What about the actual problem that a community had with it? See the link I posted above.

**Comment by jodator** [comment]
:+1: `mrgit`

**Comment by pjasiun** [comment]
:+1: for Mr git.

**Comment by mlewand** [comment]
I like `mrgit`. The name make sense for this app. I'm not concerned about the length, I'm using already `mg` alias for `mgit`, coz `mgit` is already too long 😂

**Comment by pomek** [comment]
@Reinmar, as I could see, this guy just wasn't aware that he needs to install more tools. He could miss it in docs or forget to install. Changing the name won't resolve the problem.

**Comment by jodator** [comment]
> Changing the name won't resolve the problem.

Will resolve a problem of:
- wrong package installed: `mgit` vs `mgit2
- wrong package used by `npx` command (non-initialised repo): `npx mgit sync` vs `npx mgit2 sync`.

**Comment by ma2ciek** [comment]
☝️ Yes, I have to agree with @jodator, For example, I've installed many times the `ncu` (ncu-weather-cli) instead of `npm-check-dependencies`. Both of them provide the `ncu` command.

**Comment by pomek** [comment]
Not related to the entire topic but an argument that you installed something different than you expected is not valid. Before calling `npm i whatever`, would be good to see what the `whatever` is. (https://www.npmjs.com/package/ncu explains everything in that case). This is a security check.

I don't want to block the issue. Just type the final proposition and I am going to rename the package.

**Comment by ma2ciek** [comment]
> Not related to the entire topic but an argument that you installed something different than you expected is not valid. Before calling `npm i whatever`, would be good to see what the whatever is. 

I did it installing the `npm-check-dependencies` for the first time. But later I only remembered the `ncu` because of the CLI tool and I was expecting this package to be available on the NPM.

**Comment by Reinmar** [comment]
OK, `mrgit` it is. Let's do it :)

**Comment by long-lazuli** [comment]
`alias mgr=mgit` 🎉 :)
