### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by pomek** [cksource/mgit2#86]
https://github.com/ckeditor/ckeditor5/issues/1294#issuecomment-428569470

If some command failed, mgit should change exit code and display which repo ends with an error. At this moment you can miss that something went wrong because mgit displays a very long.

**Comment by Reinmar** [comment]
> and display which repo ends with an error

It'd be enough if it wrote a big red "The command failed to execute in N repositories." at the end.

**Comment by Reinmar** [comment]
The same here:

![image](https://user-images.githubusercontent.com/156149/47441094-bd4d2b80-d7af-11e8-9ff4-18070748abd7.png)

**Comment by Reinmar** [comment]
If I had a smaller screen I wouldn't notice that.
