### ISSUE TITLE
mgit2 bootstrap should try for the second time if the repo fail

### ISSUE THREAD

**Issue by pjasiun** [cksource/mgit2#87]
I still get this error randomly when execute `mgit bootstrap` and if it is part of the bigger task, like `yarn reset` or docs building it breaks the whole flow badly, force me to fix the structure manually.

<img width="733" alt="screen shot 2018-11-02 at 12 13 21" src="https://user-images.githubusercontent.com/1166967/47912441-f9ac1600-de98-11e8-8655-f43da03dda8d.png">

Since we have no idea how to fix this error, I think we should make mgit try again in such cases, probably with some timeout. I believe this is because we reach the number of simultaneous connections to github.

**Comment by Reinmar** [comment]
Good idea!

**Comment by pjasiun** [comment]
I hope so :)

**Comment by Reinmar** [comment]
I think that the question is – does it help?

**Comment by ma2ciek** [comment]
The problem is that it's only reproducible on @pjasiun's macs 😄

**Comment by Reinmar** [comment]
And @scofalik's :> But perhaps it can be generalised to our hq's network. If you won't be able to reproduce it with 40+ repositories, ping guys there to try to check it, @pomek.

**Comment by pomek** [comment]
I am not able to reproduce it but I am still trying.

**Comment by pomek** [comment]
Does the solution described here – https://stackoverflow.com/questions/6842687/the-remote-end-hung-up-unexpectedly-while-git-cloning – help? Could you test it?
