### ISSUE TITLE
The mgit command(s) should ignore main package.

### ISSUE THREAD

**Issue by jodator** [cksource/mgit2#96]
After debugging https://github.com/ckeditor/ckeditor5-paragraph/issues/39 and talks with @Reinmar we came to conclusion that we had a bug which npm+lerna somehow hidden from us.

The problem is when package being tested requires another package that requires the main package (it might be by a `devDependencies`).

In this case it was `ckeditor5-paragraph` that requires `ckeditor5-heading` in integration tests. The `HeadingEditing` requires `Paragraph` package. It should be sufficient to omit `ckeidtor5-paragraph` when running `mgit bootstrap`.

Right now I can see that we can:
1. Use existing `--ignore` switch to simply ignore some package - it has one drawback that this has bug/feature that it only ignores immediate packages and does not ignore packages from `--ignore` if not ignored package require it
2. Add a feature that it will always ignore current package - I can see that this should only affect bootstrap as other commands kinda depends on what's inside `packages` and we only want to prevent current package to be imported into `packages/*` if required by other plugins.

cc @Reinmar, @pomek

**Comment by Reinmar** [comment]
The second option seems logically correct. If you run `mgit bootstrap` from `package-foo`, then if `package-foo` is its transient dependency, there's no point in cloning it.

**Comment by pomek** [comment]
I guess the problem is in the script that creates the `mgit.json` file. It does not care about filtering packages. So if `ckeditor5-heading` requires` ckeditor5-paragraph` (which is already the root), it should not be added to the config file.

See: https://github.com/ckeditor/ckeditor5-dev/blob/25035552eda1fd22e27fbf4b53cf79536b3f00a4/packages/ckeditor5-dev-tests/lib/bin/createmgitjsoncontent.js

From the Mgit perspective, it's nonsense to add a package which is a root to its packages. I mean:

```
|- ckeditor5-paragraph
|-- |- packages
|-- |-- |- ckeditor5-paragraph # it should not be here
```

**Comment by jodator** [comment]
> I guess the problem is in the script that creates the `mgit.json` file.

Thanks for the tip. I'll check that.

**Comment by pomek** [comment]
I was wrong. You are right guys. Mgit shouldn't install the root package as its package.

**Comment by jodator** [comment]
It looks like the fix is quite simple. Just ignore the packages that name equals to main package name in `enque()` call of `index.js`. Unfortunately this file has no tests.
